services:
  timescaledb:
    image: timescale/timescaledb:2.18.1-pg17
    container_name: timescaledb
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pulse_dev
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pulse_dev" ]
      interval: 10s
      retries: 5
      start_period: 30s

  server:
    build: .
    container_name: pulse-server
    restart: on-failure
    depends_on:
      timescaledb:
        condition: service_healthy
    ports:
      - "8083:8080"

volumes:
  timescale_data:
    driver: local
